spring.application.name=focus
server.port=8080

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mvc.servlet.path=/

spring.datasource.url=jdbc:mysql://34.64.90.95:3306/qos_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
